//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SGREntities : DbContext
    {
        public SGREntities()
            : base("name=SGREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SGR_Clientes> SGR_Clientes { get; set; }
        public virtual DbSet<SGR_Companias> SGR_Companias { get; set; }
        public virtual DbSet<SGR_Detalles_Estados> SGR_Detalles_Estados { get; set; }
        public virtual DbSet<SGR_Habitaciones> SGR_Habitaciones { get; set; }
        public virtual DbSet<SGR_Maestros> SGR_Maestros { get; set; }
        public virtual DbSet<SGR_Reservaciones> SGR_Reservaciones { get; set; }
        public virtual DbSet<SGR_Reservaciones_Habitaciones> SGR_Reservaciones_Habitaciones { get; set; }
        public virtual DbSet<SGR_Usuarios> SGR_Usuarios { get; set; }
    }
}
